theme: jekyll-theme-cayman
layout: default
title: "Delendum"
description: "We support inventions in blockchain infrastructure, private computing, and zero-knowledge proof applications"
contact: "hello@delendum.xyz"

#host: 0.0.0.0